### ISSUE TITLE
payment verification url is out dated

### ISSUE THREAD

**Issue by mwinner313** [farazmaan/Zarinpal#1]
داداش این url 
اعتبار سنجی پس از پرداخت رو تو سورس زرین پال اپدیت کن 4روز درگیرش بودم بعد فمیدم ادرسش تغییر کرده اونم توی
source  
دستی decompile کردم فهمیدم چه خبره
دمت گرم

**Comment by mwinner313** [comment]
which one ???
2.0.4,
2.0.3

**Comment by farazmaan** [comment]
2.04
یه جزئیات به من داده بودن که من از روی اون تغییرات دادم. متاسفانه اون
جزئیات مشکل داشته. ورژن آخر رو حذف میکنم
